specs-go: fix benchmark compatibility with go1.19
The go.mod defines go1.19, which does not yet support b.Loop;

    # tags.cncf.io/container-device-interface/specs-go [tags.cncf.io/container-device-interface/specs-go.test]
    Error: ./version_bench_test.go:19:10: b.Loop undefined (type *testing.B has no field or method Loop)
    FAIL	tags.cncf.io/container-device-interface/specs-go [build failed]

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>